navsat_transform:
  ros__parameters:
    frequency: 15.0
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: false
    broadcast_utm_transform: false
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: false

    odom_frame: odom
    base_link_frame: base_link
    world_frame: map
    # datum: [37.4275, -122.1697, 0.0]