ukf_node_gps:
  ros__parameters:
    frequency: 15.0
    sensor_timeout: 1.9
    transform_timeout: 0.5
    publish_tf: true            
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map
    map_frame: map            
    print_diagnostics: true
    two_d_mode: true

    odom0: /odom
    odom0_config: [ false,  false,  false,   # x y z
                    false, false, false,    # roll pitch yaw
                    true,  true,  false,   # vx vy vz
                    false, false, false,    # vroll vpitch vyaw
                    false, false, false ]  # ax ay az
    odom0_differential: true
    odom0_relative:     false
    odom0_queue_size:   10
    odom0_nodelay:      false
    # odom0_rejection_threshold: 100


    imu0: /imu/data
    imu0_config: [ false, false, false,   # x y z (
                   false, false,  true,   # roll pitch yaw 
                   false, false, false,   # vx vy vz
                   false, false,  true,   # vroll vpitch vyaw 
                   false, false,  false ]  # ax ay az (linear accel) 

    imu0_relative:      false
    imu0_differential:  false
    imu0_queue_size:    20
    imu0_nodelay:       true
    # imu0_rejection_threshold: 100
    # imu0_pose_rejection_threshold: 100
    # imu0_twist_rejection_threshold: 100
    # imu0_linear_acceleration_rejection_threshold: 100

    
    odom1: /odometry/gps
    odom1_config: [ true,  true,  false,    # x y z, removing z for now
                    false, false, false,   # roll pitch yaw
                    false, false, false,   # vx vy vz
                    false, false, false,   # vroll vpitch vyaw
                    false, false, false ]  # ax ay az
    odom1_differential: false
    odom1_relative:     false
    odom1_queue_size:   5
    odom1_nodelay:      false
    # odom1_rejection_threshold: 2.5